spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        ddl-auto: create-drop
    show-sql: true

  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:src/main/resources/database/bankapp
    username: sa
    password:

vaadin:
  servlet:
    productionMode: false